import react from "react";
import { View, Text, Button, StyleSheet, ScrollView, useWindowDimensions } from "react-native";
import Navbar from "./components/Navbar";
import { useNavigation } from '@react-navigation/native';
import Background from "./components/Background";
import Footer from "./components/Footer";
import LandingWelcome from "./components/LandingWelcome";


export default function HomeScreen(){
    const navigation = useNavigation();

    return(
            <Background>
                <Navbar />
                <ScrollView>

                    <LandingWelcome/>
                    <Text>Hello 1!</Text>
                    <Button title="Vrati me na About" onPress={() => navigation.navigate("AboutMeScreen")}></Button>
            <Text>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget pretium urna. Praesent rutrum mollis tincidunt. Cras ut odio ac metus sagittis aliquam. Quisque nec luctus enim. Aliquam at ultricies nulla, non commodo nulla. Phasellus in tempus quam. Integer metus augue, aliquam sed odio in, iaculis bibendum enim. Mauris tristique elit in erat blandit volutpat. Pellentesque accumsan interdum erat, non mollis eros iaculis vitae. Aliquam efficitur nunc ut sapien volutpat, ac posuere justo suscipit. Mauris mollis, libero et consectetur tincidunt, lacus nulla commodo elit, a scelerisque odio nulla vel diam. Duis enim arcu, auctor ac risus ut, tincidunt ultricies ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</Text>
            <Text>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget pretium urna. Praesent rutrum mollis tincidunt. Cras ut odio ac metus sagittis aliquam. Quisque nec luctus enim. Aliquam at ultricies nulla, non commodo nulla. Phasellus in tempus quam. Integer metus augue, aliquam sed odio in, iaculis bibendum enim. Mauris tristique elit in erat blandit volutpat. Pellentesque accumsan interdum erat, non mollis eros iaculis vitae. Aliquam efficitur nunc ut sapien volutpat, ac posuere justo suscipit. Mauris mollis, libero et consectetur tincidunt, lacus nulla commodo elit, a scelerisque odio nulla vel diam. Duis enim arcu, auctor ac risus ut, tincidunt ultricies ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</Text>
            <Text>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget pretium urna. Praesent rutrum mollis tincidunt. Cras ut odio ac metus sagittis aliquam. Quisque nec luctus enim. Aliquam at ultricies nulla, non commodo nulla. Phasellus in tempus quam. Integer metus augue, aliquam sed odio in, iaculis bibendum enim. Mauris tristique elit in erat blandit volutpat. Pellentesque accumsan interdum erat, non mollis eros iaculis vitae. Aliquam efficitur nunc ut sapien volutpat, ac posuere justo suscipit. Mauris mollis, libero et consectetur tincidunt, lacus nulla commodo elit, a scelerisque odio nulla vel diam. Duis enim arcu, auctor ac risus ut, tincidunt ultricies ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</Text>
            <Text>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget pretium urna. Praesent rutrum mollis tincidunt. Cras ut odio ac metus sagittis aliquam. Quisque nec luctus enim. Aliquam at ultricies nulla, non commodo nulla. Phasellus in tempus quam. Integer metus augue, aliquam sed odio in, iaculis bibendum enim. Mauris tristique elit in erat blandit volutpat. Pellentesque accumsan interdum erat, non mollis eros iaculis vitae. Aliquam efficitur nunc ut sapien volutpat, ac posuere justo suscipit. Mauris mollis, libero et consectetur tincidunt, lacus nulla commodo elit, a scelerisque odio nulla vel diam. Duis enim arcu, auctor ac risus ut, tincidunt ultricies ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</Text>
            <Text>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget pretium urna. Praesent rutrum mollis tincidunt. Cras ut odio ac metus sagittis aliquam. Quisque nec luctus enim. Aliquam at ultricies nulla, non commodo nulla. Phasellus in tempus quam. Integer metus augue, aliquam sed odio in, iaculis bibendum enim. Mauris tristique elit in erat blandit volutpat. Pellentesque accumsan interdum erat, non mollis eros iaculis vitae. Aliquam efficitur nunc ut sapien volutpat, ac posuere justo suscipit. Mauris mollis, libero et consectetur tincidunt, lacus nulla commodo elit, a scelerisque odio nulla vel diam. Duis enim arcu, auctor ac risus ut, tincidunt ultricies ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</Text>
            <Text>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget pretium urna. Praesent rutrum mollis tincidunt. Cras ut odio ac metus sagittis aliquam. Quisque nec luctus enim. Aliquam at ultricies nulla, non commodo nulla. Phasellus in tempus quam. Integer metus augue, aliquam sed odio in, iaculis bibendum enim. Mauris tristique elit in erat blandit volutpat. Pellentesque accumsan interdum erat, non mollis eros iaculis vitae. Aliquam efficitur nunc ut sapien volutpat, ac posuere justo suscipit. Mauris mollis, libero et consectetur tincidunt, lacus nulla commodo elit, a scelerisque odio nulla vel diam. Duis enim arcu, auctor ac risus ut, tincidunt ultricies ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</Text>
            <Text>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget pretium urna. Praesent rutrum mollis tincidunt. Cras ut odio ac metus sagittis aliquam. Quisque nec luctus enim. Aliquam at ultricies nulla, non commodo nulla. Phasellus in tempus quam. Integer metus augue, aliquam sed odio in, iaculis bibendum enim. Mauris tristique elit in erat blandit volutpat. Pellentesque accumsan interdum erat, non mollis eros iaculis vitae. Aliquam efficitur nunc ut sapien volutpat, ac posuere justo suscipit. Mauris mollis, libero et consectetur tincidunt, lacus nulla commodo elit, a scelerisque odio nulla vel diam. Duis enim arcu, auctor ac risus ut, tincidunt ultricies ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</Text>
            <Text>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget pretium urna. Praesent rutrum mollis tincidunt. Cras ut odio ac metus sagittis aliquam. Quisque nec luctus enim. Aliquam at ultricies nulla, non commodo nulla. Phasellus in tempus quam. Integer metus augue, aliquam sed odio in, iaculis bibendum enim. Mauris tristique elit in erat blandit volutpat. Pellentesque accumsan interdum erat, non mollis eros iaculis vitae. Aliquam efficitur nunc ut sapien volutpat, ac posuere justo suscipit. Mauris mollis, libero et consectetur tincidunt, lacus nulla commodo elit, a scelerisque odio nulla vel diam. Duis enim arcu, auctor ac risus ut, tincidunt ultricies ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</Text>
            <Text>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget pretium urna. Praesent rutrum mollis tincidunt. Cras ut odio ac metus sagittis aliquam. Quisque nec luctus enim. Aliquam at ultricies nulla, non commodo nulla. Phasellus in tempus quam. Integer metus augue, aliquam sed odio in, iaculis bibendum enim. Mauris tristique elit in erat blandit volutpat. Pellentesque accumsan interdum erat, non mollis eros iaculis vitae. Aliquam efficitur nunc ut sapien volutpat, ac posuere justo suscipit. Mauris mollis, libero et consectetur tincidunt, lacus nulla commodo elit, a scelerisque odio nulla vel diam. Duis enim arcu, auctor ac risus ut, tincidunt ultricies ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</Text>
            <Text>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget pretium urna. Praesent rutrum mollis tincidunt. Cras ut odio ac metus sagittis aliquam. Quisque nec luctus enim. Aliquam at ultricies nulla, non commodo nulla. Phasellus in tempus quam. Integer metus augue, aliquam sed odio in, iaculis bibendum enim. Mauris tristique elit in erat blandit volutpat. Pellentesque accumsan interdum erat, non mollis eros iaculis vitae. Aliquam efficitur nunc ut sapien volutpat, ac posuere justo suscipit. Mauris mollis, libero et consectetur tincidunt, lacus nulla commodo elit, a scelerisque odio nulla vel diam. Duis enim arcu, auctor ac risus ut, tincidunt ultricies ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</Text>
            <Text>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget pretium urna. Praesent rutrum mollis tincidunt. Cras ut odio ac metus sagittis aliquam. Quisque nec luctus enim. Aliquam at ultricies nulla, non commodo nulla. Phasellus in tempus quam. Integer metus augue, aliquam sed odio in, iaculis bibendum enim. Mauris tristique elit in erat blandit volutpat. Pellentesque accumsan interdum erat, non mollis eros iaculis vitae. Aliquam efficitur nunc ut sapien volutpat, ac posuere justo suscipit. Mauris mollis, libero et consectetur tincidunt, lacus nulla commodo elit, a scelerisque odio nulla vel diam. Duis enim arcu, auctor ac risus ut, tincidunt ultricies ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</Text>
            <Text>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget pretium urna. Praesent rutrum mollis tincidunt. Cras ut odio ac metus sagittis aliquam. Quisque nec luctus enim. Aliquam at ultricies nulla, non commodo nulla. Phasellus in tempus quam. Integer metus augue, aliquam sed odio in, iaculis bibendum enim. Mauris tristique elit in erat blandit volutpat. Pellentesque accumsan interdum erat, non mollis eros iaculis vitae. Aliquam efficitur nunc ut sapien volutpat, ac posuere justo suscipit. Mauris mollis, libero et consectetur tincidunt, lacus nulla commodo elit, a scelerisque odio nulla vel diam. Duis enim arcu, auctor ac risus ut, tincidunt ultricies ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</Text>
            <Text>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget pretium urna. Praesent rutrum mollis tincidunt. Cras ut odio ac metus sagittis aliquam. Quisque nec luctus enim. Aliquam at ultricies nulla, non commodo nulla. Phasellus in tempus quam. Integer metus augue, aliquam sed odio in, iaculis bibendum enim. Mauris tristique elit in erat blandit volutpat. Pellentesque accumsan interdum erat, non mollis eros iaculis vitae. Aliquam efficitur nunc ut sapien volutpat, ac posuere justo suscipit. Mauris mollis, libero et consectetur tincidunt, lacus nulla commodo elit, a scelerisque odio nulla vel diam. Duis enim arcu, auctor ac risus ut, tincidunt ultricies ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</Text>
            <Text>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget pretium urna. Praesent rutrum mollis tincidunt. Cras ut odio ac metus sagittis aliquam. Quisque nec luctus enim. Aliquam at ultricies nulla, non commodo nulla. Phasellus in tempus quam. Integer metus augue, aliquam sed odio in, iaculis bibendum enim. Mauris tristique elit in erat blandit volutpat. Pellentesque accumsan interdum erat, non mollis eros iaculis vitae. Aliquam efficitur nunc ut sapien volutpat, ac posuere justo suscipit. Mauris mollis, libero et consectetur tincidunt, lacus nulla commodo elit, a scelerisque odio nulla vel diam. Duis enim arcu, auctor ac risus ut, tincidunt ultricies ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</Text>
            <Text>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget pretium urna. Praesent rutrum mollis tincidunt. Cras ut odio ac metus sagittis aliquam. Quisque nec luctus enim. Aliquam at ultricies nulla, non commodo nulla. Phasellus in tempus quam. Integer metus augue, aliquam sed odio in, iaculis bibendum enim. Mauris tristique elit in erat blandit volutpat. Pellentesque accumsan interdum erat, non mollis eros iaculis vitae. Aliquam efficitur nunc ut sapien volutpat, ac posuere justo suscipit. Mauris mollis, libero et consectetur tincidunt, lacus nulla commodo elit, a scelerisque odio nulla vel diam. Duis enim arcu, auctor ac risus ut, tincidunt ultricies ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</Text>
            <Text>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget pretium urna. Praesent rutrum mollis tincidunt. Cras ut odio ac metus sagittis aliquam. Quisque nec luctus enim. Aliquam at ultricies nulla, non commodo nulla. Phasellus in tempus quam. Integer metus augue, aliquam sed odio in, iaculis bibendum enim. Mauris tristique elit in erat blandit volutpat. Pellentesque accumsan interdum erat, non mollis eros iaculis vitae. Aliquam efficitur nunc ut sapien volutpat, ac posuere justo suscipit. Mauris mollis, libero et consectetur tincidunt, lacus nulla commodo elit, a scelerisque odio nulla vel diam. Duis enim arcu, auctor ac risus ut, tincidunt ultricies ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</Text>
            <Text>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget pretium urna. Praesent rutrum mollis tincidunt. Cras ut odio ac metus sagittis aliquam. Quisque nec luctus enim. Aliquam at ultricies nulla, non commodo nulla. Phasellus in tempus quam. Integer metus augue, aliquam sed odio in, iaculis bibendum enim. Mauris tristique elit in erat blandit volutpat. Pellentesque accumsan interdum erat, non mollis eros iaculis vitae. Aliquam efficitur nunc ut sapien volutpat, ac posuere justo suscipit. Mauris mollis, libero et consectetur tincidunt, lacus nulla commodo elit, a scelerisque odio nulla vel diam. Duis enim arcu, auctor ac risus ut, tincidunt ultricies ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</Text>
            <Text>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget pretium urna. Praesent rutrum mollis tincidunt. Cras ut odio ac metus sagittis aliquam. Quisque nec luctus enim. Aliquam at ultricies nulla, non commodo nulla. Phasellus in tempus quam. Integer metus augue, aliquam sed odio in, iaculis bibendum enim. Mauris tristique elit in erat blandit volutpat. Pellentesque accumsan interdum erat, non mollis eros iaculis vitae. Aliquam efficitur nunc ut sapien volutpat, ac posuere justo suscipit. Mauris mollis, libero et consectetur tincidunt, lacus nulla commodo elit, a scelerisque odio nulla vel diam. Duis enim arcu, auctor ac risus ut, tincidunt ultricies ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</Text>

                    <View style={styles.footerMargin}></View>
                    <Footer/>
                </ScrollView>
            </Background>
    );

}

const styles = StyleSheet.create({

    footerMargin:{
        height: 150,
    },
});